--creating the required databases--

--expenses table to track expenses--
CREATE TABLE expenses (
  expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR2(50) NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  expense_date DATE NOT NULL,
  note VARCHAR2(200),
  sync_status VARCHAR2(10)
);
--budgets table to track budgets--
CREATE TABLE budgets (
  budget_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR2(50),
  amount NUMBER(10,2),
  start_date DATE,
  end_date DATE,
  status VARCHAR2(20)
);

--savings table to track savings--
CREATE TABLE savings (
  saving_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_name VARCHAR2(100),
  target_amount NUMBER(10,2),
  current_amount NUMBER(10,2),
  target_date DATE,
  last_entered_date DATE,
  status VARCHAR2(20)
);

--dummy data for confirmation --
INSERT INTO expenses (category, amount, expense_date, note, sync_status)
VALUES ('Food', 2500, TO_DATE('2025-10-28', 'YYYY-MM-DD'), 'Lunch', 'PENDING');

INSERT INTO budgets (category, amount, start_date, end_date, status)
VALUES ('Food', 10000, TO_DATE('2025-10-01', 'YYYY-MM-DD'), TO_DATE('2025-10-31', 'YYYY-MM-DD'), 'PENDING');

INSERT INTO savings (goal_name, target_amount, current_amount, target_date, status)
VALUES ('New Phone', 80000, 20000, TO_DATE('2025-12-31', 'YYYY-MM-DD'), 'PENDING');

--------------------------------------------------------------------------------------------------------

--procedure to add expense--
CREATE OR REPLACE PROCEDURE add_expense(category IN VARCHAR2, amount NUMBER, expense_date DATE, note VARCHAR2)
AS
 failedToInsertException EXCEPTION;
 rowCount NUMBER;
BEGIN
    INSERT INTO expenses(category, amount, expense_date, note, sync_status) VALUES(category, amount, expense_date, note, 'PENDING');
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToInsertException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Inserted Successfully');
EXCEPTION
WHEN failedToInsertException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Insert Record Check data given...!');
END;
/

--procedure to update expense--
CREATE OR REPLACE PROCEDURE update_expense(expenseId IN NUMBER, paraCategory IN VARCHAR2, paraAmount NUMBER, paraExpenseDte DATE, paraNote VARCHAR2)
AS
 failedToUpdateException EXCEPTION;
 rowCount NUMBER;
BEGIN
    UPDATE expenses SET category = paraCategory, amount = paraAmount, expense_date = paraExpenseDte, note = paraNote, sync_status = 'PENDING' WHERE expense_id = expenseId;
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToUpdateException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Update Successfully');
EXCEPTION
WHEN failedToUpdateException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Update Record Check data given...!');
END;
/

--procedure to delete expense--
CREATE OR REPLACE PROCEDURE delete_expense(expenseId IN NUMBER)
AS
 failedToDeleteException EXCEPTION;
 rowCount NUMBER;
BEGIN
    DELETE FROM expenses WHERE expense_id = expenseId;
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToDeleteException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Delete Successfully');
EXCEPTION
WHEN failedToDeleteException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Delete Record Check data given...!');
END;
/


--procedure to add budget--
CREATE OR REPLACE PROCEDURE add_budget(category IN VARCHAR2, amount NUMBER, start_date DATE, end_date DATE)
AS
 failedToInsertException EXCEPTION;
 rowCount NUMBER;
BEGIN
    INSERT INTO budgets(category, amount, start_date, end_date, status) VALUES(category, amount, start_date, end_date, 'PENDING');
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToInsertException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Inserted in Budgets Successfully');
EXCEPTION
WHEN failedToInsertException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Insert Record in Budget Check data given...!');
END;
/

--procedure to update budget--
CREATE OR REPLACE PROCEDURE update_budget(budgetId IN NUMBER, paraCategory IN VARCHAR2, paraAmount NUMBER, paraStartDate DATE, paraEndDate DATE)
AS
 failedToUpdateException EXCEPTION;
 rowCount NUMBER;
BEGIN
    UPDATE budgets SET category = paraCategory, amount = paraAmount, start_date = paraStartDate, end_date = paraEndDate, status = 'PENDING' WHERE budget_id = budgetId;
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToUpdateException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Update in Budget Successfully');
EXCEPTION
WHEN failedToUpdateException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Update Record in Budgets Check data given...!');
END;
/

--procedure to delete budget--
CREATE OR REPLACE PROCEDURE delete_budget(budgetId IN NUMBER)
AS
 failedToDeleteException EXCEPTION;
 rowCount NUMBER;
BEGIN
    DELETE FROM budgets WHERE budget_id = budgetId;
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToDeleteException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Delete from budget Successfully');
EXCEPTION
WHEN failedToDeleteException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Delete Record in budget Check data given...!');
END;
/

--procedure to add savings--
CREATE OR REPLACE PROCEDURE add_savings(goal_name IN VARCHAR2, target_amount NUMBER, current_amount NUMBER, target_date DATE, last_entered_date DATE)
AS
 failedToInsertException EXCEPTION;
 rowCount NUMBER;
BEGIN
    INSERT INTO savings(goal_name, target_amount, current_amount,target_date, last_entered_date, status) VALUES(goal_name, target_amount, current_amount, target_date, last_entered_date, 'PENDING');
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToInsertException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Inserted in savings Successfully');
EXCEPTION
WHEN failedToInsertException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Insert Record in savings Check data given...!');
END;
/

--procedure to update savings--
CREATE OR REPLACE PROCEDURE update_savings(savingsId IN NUMBER, para_goal_name IN VARCHAR2, para_target_amount NUMBER, para_current_amount NUMBER, para_target_date DATE, para_last_entered_date DATE)
AS
 failedToUpdateException EXCEPTION;
 rowCount NUMBER;
BEGIN
    UPDATE savings SET goal_name = para_goal_name, target_amount = para_target_amount, current_amount = para_current_amount, target_date = para_target_date, last_entered_date = para_last_entered_date, status = 'PENDING' WHERE saving_id = savingsId;
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToUpdateException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Update in savings Successfully');
EXCEPTION
WHEN failedToUpdateException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Update Record in savings Check data given...!');
END;
/

--procedure to delete savings--
CREATE OR REPLACE PROCEDURE delete_savings(savingsId IN NUMBER)
AS
 failedToDeleteException EXCEPTION;
 rowCount NUMBER;
BEGIN
    DELETE FROM savings WHERE saving_id = savingsId;
    COMMIT;
    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToDeleteException;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Record Delete from savings Successfully');
EXCEPTION
WHEN failedToDeleteException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to Delete Record from savings Check data given...!');
END;
/

--------------------------------------------------------
--procedure to sync data from sqlite to oracle--

--================= sync_expenses =================
CREATE OR REPLACE PROCEDURE sync_expenses(
    p_id IN NUMBER,
    p_category IN VARCHAR2,
    p_amount IN NUMBER,
    p_expense_date DATE,
    p_note VARCHAR2
)
AS
    failedToInsertException EXCEPTION;
    rowCount NUMBER;
BEGIN
    IF p_id IS NOT NULL THEN
        UPDATE expenses
        SET category = p_category,
            amount = p_amount,
            expense_date = p_expense_date,
            note = p_note,
            sync_status = 'SYNCED'
        WHERE expense_id = p_id;
    ELSE
        INSERT INTO expenses(category, amount, expense_date, note, sync_status)
        VALUES(p_category, p_amount, p_expense_date, p_note, 'SYNCED');
    END IF;

    COMMIT;

    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToInsertException;
    END IF;

    DBMS_OUTPUT.PUT_LINE('Expense record inserted/updated successfully');

EXCEPTION
WHEN failedToInsertException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to insert/update expense. Check data!');
END;
/

--================= sync_budgets =================
CREATE OR REPLACE PROCEDURE sync_budgets(
    p_id IN NUMBER,
    p_category IN VARCHAR2,
    p_amount IN NUMBER,
    p_start_date DATE,
    p_end_date DATE
)
AS
    failedToInsertException EXCEPTION;
    rowCount NUMBER;
BEGIN
    IF p_id IS NOT NULL THEN
        UPDATE budgets
        SET category = p_category,
            amount = p_amount,
            start_date = p_start_date,
            end_date = p_end_date,
            status = 'SYNCED'
        WHERE budget_id = p_id;
    ELSE
        INSERT INTO budgets(category, amount, start_date, end_date, status)
        VALUES(p_category, p_amount, p_start_date, p_end_date, 'SYNCED');
    END IF;

    COMMIT;

    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToInsertException;
    END IF;

    DBMS_OUTPUT.PUT_LINE('Budget record inserted/updated successfully');

EXCEPTION
WHEN failedToInsertException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to insert/update budget. Check data!');
END;
/

--================= sync_savings =================
CREATE OR REPLACE PROCEDURE sync_savings(
    p_id IN NUMBER,
    p_goal_name IN VARCHAR2,
    p_target_amount IN NUMBER,
    p_current_amount IN NUMBER,
    p_target_date DATE,
    p_last_entered_date DATE
)
AS
    failedToInsertException EXCEPTION;
    rowCount NUMBER;
BEGIN
    IF p_id IS NOT NULL THEN
        UPDATE savings
        SET goal_name = p_goal_name,
            target_amount = p_target_amount,
            current_amount = p_current_amount,
            target_date = p_target_date,
            last_entered_date = p_last_entered_date,
            status = 'SYNCED'
        WHERE saving_id = p_id;
    ELSE
        INSERT INTO savings(goal_name, target_amount, current_amount, target_date, last_entered_date, status)
        VALUES(p_goal_name, p_target_amount, p_current_amount, p_target_date, p_last_entered_date, 'SYNCED');
    END IF;

    COMMIT;

    rowCount := SQL%ROWCOUNT;
    IF rowCount = 0 THEN
        RAISE failedToInsertException;
    END IF;

    DBMS_OUTPUT.PUT_LINE('Savings record inserted/updated successfully');

EXCEPTION
WHEN failedToInsertException THEN
    DBMS_OUTPUT.PUT_LINE('Failed to insert/update savings. Check data!');
END;
/

-- expenses delete
CREATE OR REPLACE PROCEDURE sync_expenses_delete(
    p_id IN NUMBER,
    p_category IN VARCHAR2,
    p_amount IN NUMBER,
    p_expense_date DATE,
    p_note VARCHAR2
)
AS
BEGIN
    IF p_id IS NOT NULL THEN
        UPDATE expenses
        SET category = p_category,
            amount = p_amount,
            expense_date = p_expense_date,
            note = p_note,
            sync_status = 'DELETED'
        WHERE expense_id = p_id;
    ELSE
        INSERT INTO expenses(category, amount, expense_date, note, sync_status)
        VALUES(p_category, p_amount, p_expense_date, p_note, 'DELETED');
    END IF;
    COMMIT;
END;
/

-- budgets delete
CREATE OR REPLACE PROCEDURE sync_budgets_delete(
    p_id IN NUMBER,
    p_category IN VARCHAR2,
    p_amount IN NUMBER,
    p_start_date DATE,
    p_end_date DATE
)
AS
BEGIN
    IF p_id IS NOT NULL THEN
        UPDATE budgets
        SET category = p_category,
            amount = p_amount,
            start_date = p_start_date,
            end_date = p_end_date,
            status = 'DELETED'
        WHERE budget_id = p_id;
    ELSE
        INSERT INTO budgets(category, amount, start_date, end_date, status)
        VALUES(p_category, p_amount, p_start_date, p_end_date, 'DELETED');
    END IF;
    COMMIT;
END;
/

-- savings delete
CREATE OR REPLACE PROCEDURE sync_savings_delete(
    p_id IN NUMBER,
    p_goal_name IN VARCHAR2,
    p_target_amount IN NUMBER,
    p_current_amount IN NUMBER,
    p_target_date DATE,
    p_last_entered_date DATE
)
AS
BEGIN
    IF p_id IS NOT NULL THEN
        UPDATE savings
        SET goal_name = p_goal_name,
            target_amount = p_target_amount,
            current_amount = p_current_amount,
            target_date = p_target_date,
            last_entered_date = p_last_entered_date,
            status = 'DELETED'
        WHERE saving_id = p_id;
    ELSE
        INSERT INTO savings(goal_name, target_amount, current_amount, target_date, last_entered_date, status)
        VALUES(p_goal_name, p_target_amount, p_current_amount, p_target_date, p_last_entered_date, 'DELETED');
    END IF;
    COMMIT;
END;
/


----------------------------------------------------------------------------------------
--functions for calculations--
CREATE OR REPLACE PROCEDURE get_pending_expenses(p_cursor OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN p_cursor FOR
    SELECT expense_id AS id,
           category,
           amount,
           expense_date,
           note
    FROM expenses
    WHERE sync_status = 'PENDING';
END;
/

CREATE OR REPLACE PROCEDURE get_pending_budgets(p_cursor OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN p_cursor FOR
    SELECT budget_id AS id,
           category,
           amount,
           start_date,
           end_date
    FROM budgets
    WHERE status = 'PENDING';
END;
/

CREATE OR REPLACE PROCEDURE get_pending_savings(p_cursor OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN p_cursor FOR
    SELECT saving_id AS id,
           goal_name,
           target_amount,
           current_amount,
           target_date,
           last_entered_date
    FROM savings
    WHERE status = 'PENDING';
END;
/


--calculate total expense for a given month--
--calculate total expense for a given category--
--calculate total savings--
--calculate remaining total budget for a category--
--get saving progress for a category-- 

--triggers for the program--

--sync on log in--
--pending on update expense--
--pending on update budget--
--budget limit--

--views for the program--

--expense summary view--
--monthly expense view--
--savings progress view--

--materialized views--

--monthly expenses--
--category expenses 
--budgets vs expenses --

--select cursor procedures--

--updates--
--fuctions for calculate--
  
-- calculate total expense for a given month and year
CREATE OR REPLACE FUNCTION get_monthly_total_expense(
    p_month IN NUMBER,
    p_year IN NUMBER
)
RETURN NUMBER
IS
    v_total_expense NUMBER(10, 2);
BEGIN
    SELECT NVL(SUM(amount), 0)
    INTO v_total_expense
    FROM expenses
    WHERE EXTRACT(MONTH FROM expense_date) = p_month
    AND EXTRACT(YEAR FROM expense_date) = p_year;

    RETURN v_total_expense;
END;
/

-- calculate total expense for a given category
CREATE OR REPLACE FUNCTION get_category_total_expense(
    p_category IN VARCHAR2
)
RETURN NUMBER
IS
    v_total_expense NUMBER(10, 2);
BEGIN
    SELECT NVL(SUM(amount), 0)
    INTO v_total_expense
    FROM expenses
    WHERE category = p_category;

    RETURN v_total_expense;
END;
/

-- calculate total savings (sum of current_amount across all goals)
CREATE OR REPLACE FUNCTION get_total_current_savings
RETURN NUMBER
IS
    v_total_savings NUMBER(10, 2);
BEGIN
    SELECT NVL(SUM(current_amount), 0)
    INTO v_total_savings
    FROM savings;

    RETURN v_total_savings;
END;
/

-- calculate remaining total budget for a category
CREATE OR REPLACE FUNCTION get_remaining_budget(
    p_category IN VARCHAR2,
    p_date IN DATE DEFAULT SYSDATE
)
RETURN NUMBER
IS
    v_budget_amount NUMBER(10, 2);
    v_spent_amount NUMBER(10, 2);
BEGIN
    -- Get the active budget amount for the category covering the given date
    SELECT NVL(MAX(amount), 0)
    INTO v_budget_amount
    FROM budgets
    WHERE category = p_category
    AND p_date BETWEEN start_date AND end_date
    AND status = 'ACTIVE'; -- Assuming 'ACTIVE' is the status for current budgets

    -- Get total expenses for that category within the budget period
    -- This assumes expenses are within the current active budget period
    SELECT NVL(SUM(e.amount), 0)
    INTO v_spent_amount
    FROM expenses e
    JOIN budgets b ON e.category = b.category
    WHERE b.category = p_category
    AND e.expense_date BETWEEN b.start_date AND b.end_date
    AND b.start_date = ( -- Find the start date of the current ACTIVE budget for context
        SELECT MAX(start_date)
        FROM budgets
        WHERE category = p_category
        AND p_date BETWEEN start_date AND end_date
    );

    RETURN v_budget_amount - v_spent_amount;
END;
/

-- get saving progress for a category (as a percentage)
CREATE OR REPLACE FUNCTION get_saving_progress_percent(
    p_saving_id IN NUMBER
)
RETURN NUMBER
IS
    v_target_amount NUMBER(10, 2);
    v_current_amount NUMBER(10, 2);
    v_progress_percent NUMBER(5, 2);
BEGIN
    SELECT target_amount, current_amount
    INTO v_target_amount, v_current_amount
    FROM savings
    WHERE saving_id = p_saving_id;

    IF v_target_amount > 0 THEN
        v_progress_percent := (v_current_amount / v_target_amount) * 100;
        RETURN v_progress_percent;
    ELSE
        -- Return 0 or handle error if target amount is zero
        RETURN 0;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL; -- Or raise an application error
END;
/

--triggers--
-- pending on update expense
CREATE OR REPLACE TRIGGER trg_expense_update_status
BEFORE UPDATE OF category, amount, expense_date, note ON expenses
FOR EACH ROW
BEGIN
    -- Set sync_status to 'PENDING' if any tracked field changes
    IF :OLD.category != :NEW.category OR
       :OLD.amount != :NEW.amount OR
       :OLD.expense_date != :NEW.expense_date OR
       NVL(:OLD.note, 'X') != NVL(:NEW.note, 'X') -- Handle potential NULL notes
    THEN
        :NEW.sync_status := 'PENDING';
    END IF;
END;
/

-- pending on update budget
CREATE OR REPLACE TRIGGER trg_budget_update_status
BEFORE UPDATE OF category, amount, start_date, end_date ON budgets
FOR EACH ROW
BEGIN
    -- Set status to 'PENDING' if any tracked field changes
    IF :OLD.category != :NEW.category OR
       :OLD.amount != :NEW.amount OR
       :OLD.start_date != :NEW.start_date OR
       :OLD.end_date != :NEW.end_date
    THEN
        :NEW.status := 'PENDING';
    END IF;
END;
/

-- budget limit (Preventing expense if it exceeds the active budget)
CREATE OR REPLACE TRIGGER trg_budget_limit
BEFORE INSERT ON expenses
FOR EACH ROW
DECLARE
    v_remaining_budget NUMBER(10, 2);
    e_budget_exceeded EXCEPTION;
BEGIN
    -- Check the remaining budget for the expense category on the expense date
    v_remaining_budget := get_remaining_budget(:NEW.category, :NEW.expense_date);

    IF v_remaining_budget < :NEW.amount THEN
        RAISE e_budget_exceeded;
    END IF;

EXCEPTION
    WHEN e_budget_exceeded THEN
        RAISE_APPLICATION_ERROR(-20001, 'Expense of ' || :NEW.amount || ' for category ' || :NEW.category || ' exceeds the remaining budget of ' || v_remaining_budget || '.');
END;
/

--views--
-- expense summary view (Total spent per category across all time)
CREATE OR REPLACE VIEW expense_summary_view AS
SELECT
    category,
    COUNT(expense_id) AS total_transactions,
    SUM(amount) AS total_spent
FROM
    expenses
GROUP BY
    category
ORDER BY
    total_spent DESC;

-- monthly expense view (Total spent per month)
CREATE OR REPLACE VIEW monthly_expense_view AS
SELECT
    TO_CHAR(expense_date, 'YYYY-MM') AS expense_month,
    EXTRACT(YEAR FROM expense_date) AS expense_year,
    EXTRACT(MONTH FROM expense_date) AS expense_month_num,
    SUM(amount) AS total_spent
FROM
    expenses
GROUP BY
    TO_CHAR(expense_date, 'YYYY-MM'),
    EXTRACT(YEAR FROM expense_date),
    EXTRACT(MONTH FROM expense_date)
ORDER BY
    expense_year DESC, expense_month_num DESC;

-- savings progress view (Goal details including progress percentage)
CREATE OR REPLACE VIEW savings_progress_view AS
SELECT
    saving_id,
    goal_name,
    target_amount,
    current_amount,
    target_date,
    status,
    (current_amount / target_amount) * 100 AS progress_percent
FROM
    savings
WHERE
    target_amount > 0;

--other materialize views for performance--
-- monthly expenses Materialized View (Refresh daily for faster reporting)
CREATE MATERIALIZED VIEW mv_monthly_expenses
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND -- or ON COMMIT/FAST if logs are set up
AS
SELECT
    TRUNC(expense_date, 'MM') AS expense_month_start,
    SUM(amount) AS monthly_total_spent
FROM
    expenses
GROUP BY
    TRUNC(expense_date, 'MM');

-- category expenses Materialized View (Total spent per category, for dashboards)
CREATE MATERIALIZED VIEW mv_category_expenses
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    category,
    SUM(amount) AS category_total_spent
FROM
    expenses
GROUP BY
    category;

-- budgets vs expenses Materialized View (Comparison of budget and actual spend)
CREATE MATERIALIZED VIEW mv_budgets_vs_expenses
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    b.budget_id,
    b.category,
    b.start_date,
    b.end_date,
    b.amount AS budget_amount,
    NVL(SUM(e.amount), 0) AS actual_spent,
    b.amount - NVL(SUM(e.amount), 0) AS remaining_budget
FROM
    budgets b
LEFT JOIN
    expenses e
    ON b.category = e.category
    AND e.expense_date BETWEEN b.start_date AND b.end_date
GROUP BY
    b.budget_id, b.category, b.start_date, b.end_date, b.amount;





--sync for sqlite cursors--
